/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateEscrowRouteImport } from './routes/create-escrow'
import { Route as MyEscrowsRouteImport } from './routes/my-escrows'
import { Route as EscrowsAddressRouteImport } from './routes/escrows.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateEscrowRoute = CreateEscrowRouteImport.update({
  id: '/create-escrow',
  path: '/create-escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEscrowsRoute = MyEscrowsRouteImport.update({
  id: '/my-escrows',
  path: '/my-escrows',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowsAddressRoute = EscrowsAddressRouteImport.update({
  id: '/escrows/$address',
  path: '/escrows/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-escrow': typeof CreateEscrowRoute
  '/my-escrows': typeof MyEscrowsRoute
  '/escrows/$address': typeof EscrowsAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-escrow': typeof CreateEscrowRoute
  '/my-escrows': typeof MyEscrowsRoute
  '/escrows/$address': typeof EscrowsAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-escrow': typeof CreateEscrowRoute
  '/my-escrows': typeof MyEscrowsRoute
  '/escrows/$address': typeof EscrowsAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-escrow' | '/my-escrows' | '/escrows/$address'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-escrow' | '/my-escrows' | '/escrows/$address'
  id: '__root__' | '/' | '/create-escrow' | '/my-escrows' | '/escrows/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateEscrowRoute: typeof CreateEscrowRoute
  MyEscrowsRoute: typeof MyEscrowsRoute
  EscrowsAddressRoute: typeof EscrowsAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-escrow': {
      id: '/create-escrow'
      path: '/create-escrow'
      fullPath: '/create-escrow'
      preLoaderRoute: typeof CreateEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-escrows': {
      id: '/my-escrows'
      path: '/my-escrows'
      fullPath: '/my-escrows'
      preLoaderRoute: typeof MyEscrowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrows/$address': {
      id: '/escrows/$address'
      path: '/escrows/$address'
      fullPath: '/escrows/$address'
      preLoaderRoute: typeof EscrowsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateEscrowRoute: CreateEscrowRoute,
  MyEscrowsRoute: MyEscrowsRoute,
  EscrowsAddressRoute: EscrowsAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
