/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscrowsAddressRouteImport } from './routes/escrows.$address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowsAddressRoute = EscrowsAddressRouteImport.update({
  id: '/escrows/$address',
  path: '/escrows/$address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escrows/$address': typeof EscrowsAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/escrows/$address': typeof EscrowsAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escrows/$address': typeof EscrowsAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/escrows/$address'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/escrows/$address'
  id: '__root__' | '/' | '/escrows/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscrowsAddressRoute: typeof EscrowsAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrows/$address': {
      id: '/escrows/$address'
      path: '/escrows/$address'
      fullPath: '/escrows/$address'
      preLoaderRoute: typeof EscrowsAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscrowsAddressRoute: EscrowsAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
