@startuml

interface KeyStorer {
    +Void importBirthday(BlockHeight birthday)
    +BlockHeight exportBirthday()
    +Void importSeed ([UInt8] bytes)
    +[UInt8] exportSeed()
    +Void importPhrase(seedPhrase: String)
    +String exportPhrase()
    +Void saveKeys(keys: [String])
    +[String] getKeys()
    +Void nukeWallet()
}

class SeedManager {
    -SeedManager default
    +{static} SeedManager defaultManager()
}

enum SeedManagerError {
    alreadyImported
    uninitializedWallet
}

KeyStorer <|-- SeedManager

SeedManager -[dotted]-> SeedManagerError : throws
@enduml