import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "../../..");
const contracts = ["EscrowFactory", "Escrow"];
const output = [];

for (const name of contracts) {
  const artifactPath = resolve(root, `artifacts/contracts/${name}.sol/${name}.json`);
  const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
  output.push(
    `export const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
  );
}

const target = resolve(import.meta.dirname, "../src/index.ts");
const generated = `// Generated by scripts/generate.mjs. Do not edit.\n\n${output.join("\n\n")}\n`;

if (process.argv.includes("--check")) {
  const current = await readFile(target, "utf8").catch(() => "");
  if (current !== generated) {
    console.error("Generated contract bindings are stale. Run: pnpm contracts:generate");
    process.exitCode = 1;
  }
} else {
  await mkdir(resolve(import.meta.dirname, "../src"), { recursive: true });
  await writeFile(target, generated);
}
